# Generated by Django 4.1.3 on 2023-02-12 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0002_topic_savedarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedarticle',
            name='article_savers',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_followers',
        ),
        migrations.AddField(
            model_name='savedarticle',
            name='saver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='article_savers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='follower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='topic_followers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedarticle',
            name='thumbnailUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.TextField(default='', max_length=25),
        ),
    ]
