# Generated by Django 4.1.3 on 2023-02-12 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0004_alter_savedarticle_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='saver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_saved_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
