# Generated by Django 4.1.3 on 2023-02-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0005_alter_savedarticle_saver'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedarticle',
            name='articleUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
