# Generated by Django 4.1.3 on 2023-02-15 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0006_savedarticle_articleurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
