# Generated by Django 4.1.3 on 2023-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0007_alter_topic_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
