# Generated by Django 4.1.3 on 2023-02-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0008_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
