# Generated by Django 4.1.3 on 2023-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalNews', '0009_remove_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
